[package]
name = "rusty-rlg"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.17.0"
rand = "0.8.5"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.15"
tracing = "0.1.36"

